PUT localhost:8080/api/users/5
Content-Type: application/json

{
  "firstName": "Birendra",
  "lastName": "Shrestha",
  "email": "birendra.m@gmail.com",
  "password": "encrypted0123",
  "role": "USER"
}